/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ViewIndexRouteImport } from './routes/view/index'
import { Route as TestIndexRouteImport } from './routes/test/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as HistoryIndexRouteImport } from './routes/history/index'
import { Route as ViewSubFolderIdRouteImport } from './routes/view/$subFolderId'
import { Route as SettingsStorageRouteImport } from './routes/settings/storage'
import { Route as SettingsLanguageRouteImport } from './routes/settings/language'
import { Route as SettingsConnectedAccountsRouteImport } from './routes/settings/connected-accounts'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as SettingsApiKeysRouteImport } from './routes/settings/api-keys'
import { Route as ApiNovel_handlerRouteImport } from './routes/api/novel_handler'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewIndexRoute = ViewIndexRouteImport.update({
  id: '/view/',
  path: '/view/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewSubFolderIdRoute = ViewSubFolderIdRouteImport.update({
  id: '/view/$subFolderId',
  path: '/view/$subFolderId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsStorageRoute = SettingsStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsLanguageRoute = SettingsLanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsConnectedAccountsRoute =
  SettingsConnectedAccountsRouteImport.update({
    id: '/connected-accounts',
    path: '/connected-accounts',
    getParentRoute: () => SettingsRouteRoute,
  } as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsApiKeysRoute = SettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const ApiNovel_handlerRoute = ApiNovel_handlerRouteImport.update({
  id: '/api/novel_handler',
  path: '/api/novel_handler',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/api/novel_handler': typeof ApiNovel_handlerRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/connected-accounts': typeof SettingsConnectedAccountsRoute
  '/settings/language': typeof SettingsLanguageRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/view/$subFolderId': typeof ViewSubFolderIdRoute
  '/history/': typeof HistoryIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/test/': typeof TestIndexRoute
  '/view/': typeof ViewIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/novel_handler': typeof ApiNovel_handlerRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/connected-accounts': typeof SettingsConnectedAccountsRoute
  '/settings/language': typeof SettingsLanguageRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/view/$subFolderId': typeof ViewSubFolderIdRoute
  '/history': typeof HistoryIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/test': typeof TestIndexRoute
  '/view': typeof ViewIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/api/novel_handler': typeof ApiNovel_handlerRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/connected-accounts': typeof SettingsConnectedAccountsRoute
  '/settings/language': typeof SettingsLanguageRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/view/$subFolderId': typeof ViewSubFolderIdRoute
  '/history/': typeof HistoryIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/test/': typeof TestIndexRoute
  '/view/': typeof ViewIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/api/novel_handler'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/connected-accounts'
    | '/settings/language'
    | '/settings/storage'
    | '/view/$subFolderId'
    | '/history/'
    | '/settings/'
    | '/test/'
    | '/view/'
    | '/api/auth/$'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/novel_handler'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/connected-accounts'
    | '/settings/language'
    | '/settings/storage'
    | '/view/$subFolderId'
    | '/history'
    | '/settings'
    | '/test'
    | '/view'
    | '/api/auth/$'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/api/novel_handler'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/connected-accounts'
    | '/settings/language'
    | '/settings/storage'
    | '/view/$subFolderId'
    | '/history/'
    | '/settings/'
    | '/test/'
    | '/view/'
    | '/api/auth/$'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  ApiNovel_handlerRoute: typeof ApiNovel_handlerRoute
  ViewSubFolderIdRoute: typeof ViewSubFolderIdRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
  TestIndexRoute: typeof TestIndexRoute
  ViewIndexRoute: typeof ViewIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/': {
      id: '/view/'
      path: '/view'
      fullPath: '/view/'
      preLoaderRoute: typeof ViewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/$subFolderId': {
      id: '/view/$subFolderId'
      path: '/view/$subFolderId'
      fullPath: '/view/$subFolderId'
      preLoaderRoute: typeof ViewSubFolderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/storage': {
      id: '/settings/storage'
      path: '/storage'
      fullPath: '/settings/storage'
      preLoaderRoute: typeof SettingsStorageRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/language': {
      id: '/settings/language'
      path: '/language'
      fullPath: '/settings/language'
      preLoaderRoute: typeof SettingsLanguageRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/connected-accounts': {
      id: '/settings/connected-accounts'
      path: '/connected-accounts'
      fullPath: '/settings/connected-accounts'
      preLoaderRoute: typeof SettingsConnectedAccountsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/api-keys': {
      id: '/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof SettingsApiKeysRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/api/novel_handler': {
      id: '/api/novel_handler'
      path: '/api/novel_handler'
      fullPath: '/api/novel_handler'
      preLoaderRoute: typeof ApiNovel_handlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsApiKeysRoute: typeof SettingsApiKeysRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsConnectedAccountsRoute: typeof SettingsConnectedAccountsRoute
  SettingsLanguageRoute: typeof SettingsLanguageRoute
  SettingsStorageRoute: typeof SettingsStorageRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsApiKeysRoute: SettingsApiKeysRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsConnectedAccountsRoute: SettingsConnectedAccountsRoute,
  SettingsLanguageRoute: SettingsLanguageRoute,
  SettingsStorageRoute: SettingsStorageRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  ApiNovel_handlerRoute: ApiNovel_handlerRoute,
  ViewSubFolderIdRoute: ViewSubFolderIdRoute,
  HistoryIndexRoute: HistoryIndexRoute,
  TestIndexRoute: TestIndexRoute,
  ViewIndexRoute: ViewIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
